name: pytest
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install poetry
	      pip poetry build
          uses: paambaati/codeclimate-action@v2.7.5
          env:
            CC_TEST_REPORTER_ID: 5b62415018c8fc45160a4bea8fd46ce3f7d6bb03533b6bc61111f0355d9e32e2
          with:
            coverageCommand: make pytest_lint